services:
  api:
    build:
      context: .
      dockerfile: src/LoanHub.Search.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  web:
    build:
      context: src/LoanHub.Search.Web
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - api
