services:
  api:
    build:
      context: .
      dockerfile: src/LoanHub.Search.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Applications: Host=db;Port=5432;Database=loanhub;Username=loanhub;Password=loanhub
    depends_on:
      - db

  web:
    build:
      context: src/LoanHub.Search.Web
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - api

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: loanhub
      POSTGRES_USER: loanhub
      POSTGRES_PASSWORD: loanhub
    ports:
      - "5432:5432"
    volumes:
      - loanhub-postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@loanhub.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - loanhub-pgadmin:/var/lib/pgadmin

volumes:
  loanhub-postgres:
  loanhub-pgadmin:
